# client/web/BUILD.bazel
load("@rules_python//python:defs.bzl", "py_binary")
load("@rules_rust//rust:defs.bzl", "rust_shared_library")
load("@rules_rust_wasm_bindgen//:defs.bzl", "rust_wasm_bindgen")

rust_shared_library(
    name = "web_wasm",
    srcs = ["src/lib.rs"],
    edition = "2021",
    deps = [
        "@crates//:wasm-bindgen",
        "@crates//:web-sys",
        "@crates//:js-sys",
    ],
)

rust_wasm_bindgen(
    name = "generate_bindings",
    target = "web",
    wasm_file = ":web_wasm",
)

py_binary(
    name = "serve",
    srcs = ["server.py"],
    data = [
        "static/index.html",
        "static/style.css",
        "src/main.js",
        "src/worker.js",
        ":generate_bindings",
    ],
    main = "server.py",
)

exports_files([
    "src/lib.rs",
    "src/main.js",
    "src/worker.js",
    "server.py",
    "static/index.html",
    "static/style.css",
])
