load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")
package(default_visibility = ["//visibility:public"])


rust_library(
    name = "window",
    srcs = ["window.rs"],
    deps = [
        "@crates//:winit",
    ],
)


rust_binary(
    name = "vulkan_window_main",
    srcs = ["main.rs"],
    compile_data = ["//client/winit/common:knight.png"],
    deps = [
        ":window",
        "@crates//:winit",
        "@crates//:vulkanalia",
        "@crates//:clap",
        "@crates//:nalgebra",
        "@crates//:image",
        "//client/common:handle",
        "//client/winit/common:vulkan_context",
        "//client/winit/common:primitives",
        "//client/winit/common:vulkan_texture",
        "//client/winit/basic_pipeline",
        "//client/winit/indirect_pipeline",
    ],
)